spring:
  application:
    name: splitwise
  # MySQL Properties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/split_bill
    username: hasher
    password: password@128
  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

# Server Properties
server:
  port: 9090
  servlet:
    contextPath: /v1